### ISSUE TITLE
Postal Code search not working

### ISSUE THREAD

**Issue by rhubley** [shayqn/parle#16]
Used several postal codes from Nova Scotia and they did not work. They did work in the openparliament.ca database

**Comment by shayqn** [comment]
Can you give some examples?

**Comment by rhubley** [comment]
B2T1H6, B2X3L8

**Comment by bnfld** [comment]
resolved in latest commit, it was a silly problem with some results from the opennorth riding API having a different number of hyphens than the riding names in the database. all non-alphabetic characters are now ignored in riding comparison.
