### ISSUE TITLE
Enter key in Search box has odd behaviour

### ISSUE THREAD

**Issue by rhubley** [shayqn/parle#17]
Hitting the enter key after entering a search term will cause the page to refresh without remembering the search term. 

Auto filtering works great but sometimes I will press enter before knowing the list is being filtered. Enter key should be caught and prevented from submitting form.

**Comment by bnfld** [comment]
Thanks for taking the time to point that out, it indeed should be preventing that behaviour.

**Comment by bnfld** [comment]
fixed in latest commit
